### ISSUE TITLE
Pacman for ever

### ISSUE THREAD

**Issue by isAAAc** [dwaaan/HRConvert2-Docker#1]
Hello, 
i just installed and used your docker app, 
but i have an issue (or not) :
i upload a .pdf and tray to convert it in docx
but the green pacman looks eating for ever, 
i tried with method 1 and method 2, 

the pacman is still eating, i'll wait tomorow , but i think it's broken

thx for your help

**Comment by dwaaan** [comment]
thanks for your report, will test and get back to you within few days

**Comment by isAAAc** [comment]
no answer since 2019/12  i close the issue

**Comment by zelon88** [comment]
Hello,

Do you have a log file? These are stored in /var/www/html/HRProprietary/HRConvert2/Logs by default.

Also, it appears this Docker repo is using HRConvert2 v2.4. The latest up stream version at https://github.com/zelon88/HRConvert2 is at v2.6. Updating to the latest version may solve your issue.

I am the maintainer of the upstream repo, and I just made a release at v2.6 specifically so that updating this Docker repo is easier. I don't use Docker as part of my workflow, but I will prepare a pull request to start using the latest release instead.
